# Generated by Django 3.0.7 on 2020-06-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200624_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
